function(add_render_executable NAME)
    FILE(GLOB_RECURSE SOURCES Source/*.cpp)
    add_executable(${NAME} ${SOURCES})
    target_include_directories(${NAME} PUBLIC Include)
    target_link_libraries(${NAME} PUBLIC SwiftRender glfw Utility STBI)
    add_dependencies(${NAME} CompileShaders)
    add_dependencies(${NAME} CopyResources)
endfunction()

function(add_render_library NAME)
    FILE(GLOB_RECURSE SOURCES Source/*.cpp)
    add_library(${NAME} ${SOURCES})
    target_include_directories(${NAME} PUBLIC Include ${CMAKE_SOURCE_DIR}/External/GLFW/include)
    target_link_libraries(${NAME} PUBLIC SwiftRender glfw fastgltf::fastgltf)
endfunction()